name: StrawberryOS Base
id: strawberryos-base

pre-init:
  commands:
    - rm -rf rootfs* os-bootstrap
    - wget https://github.com/Strawberry-Foundations/sbos-scripts/raw/main/os-bootstrap
    - chmod a+x os-bootstrap
    - mkdir rootfs
    - export DEBIAN_FRONTEND=noninteractive
    - DEBIAN_FRONTEND=noninteractive
    - apt install debootstrap bubblewrap
    - DEBIAN_FRONTEND=noninteractive ./os-bootstrap install -t rootfs
    - cd rootfs
    - tar -cf ../rootfs.tar .

init:
  base: scratch
  files:
    - source: rootfs.tar
      destination: /

post-init:
  commands:
    - wget https://raw.githubusercontent.com/Strawberry-Foundations/sbos-scripts/main/neofetch -O /usr/bin/neofetch
    - chmod a+x /usr/bin/neofetch
