name: StrawberryOS Base
id: strawberryos-base

pre-init:
  commands:
    - rm -rf rootfs* os-bootstrap
    - wget https://github.com/Strawberry-Foundations/sbos-scripts/raw/main/os-bootstrap
    - chmod a+x os-bootstrap
    - mkdir rootfs
    - export DEBIAN_FRONTEND=noninteractive
    - DEBIAN_FRONTEND=noninteractive
    - apt install debootstrap bubblewrap wget
    - DEBIAN_FRONTEND=noninteractive ./os-bootstrap install -t rootfs utils
    - wget https://raw.githubusercontent.com/Strawberry-Foundations/sbos-scripts/main/neofetch -O /workdir/rootfs/usr/bin/neofetch
    - chmod a+x /workdir/rootfs/usr/bin/neofetch
    - tar -cvf rootfs.tar -C rootfs/ .

init:
  base: scratch
  files:
    - source: rootfs.tar
      destination: /
